console.log('instrumented foo');

if (typeof __coverage__ === 'undefined') { __coverage__ = {}; }
if (!__coverage__['C:\\git\\gt\\examples\\browser\\src\\Foo.js']) {
   __coverage__['C:\\git\\gt\\examples\\browser\\src\\Foo.js'] = {"path":"C:\\git\\gt\\examples\\browser\\src\\Foo.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0},"b":{"1":[0,0]},"f":{"1":0,"2":0,"3":0},"fnMap":{"1":{"name":"(anonymous_1)","line":1,"loc":{"start":{"line":1,"column":11},"end":{"line":1,"column":23}}},"2":{"name":"(anonymous_2)","line":2,"loc":{"start":{"line":2,"column":8},"end":{"line":2,"column":19}}},"3":{"name":"notCalled","line":10,"loc":{"start":{"line":10,"column":0},"end":{"line":10,"column":21}}}},"statementMap":{"1":{"start":{"line":1,"column":0},"end":{"line":8,"column":3}},"2":{"start":{"line":2,"column":1},"end":{"line":7,"column":3}},"3":{"start":{"line":3,"column":2},"end":{"line":5,"column":3}},"4":{"start":{"line":4,"column":3},"end":{"line":4,"column":16}},"5":{"start":{"line":6,"column":2},"end":{"line":6,"column":15}},"6":{"start":{"line":10,"column":0},"end":{"line":12,"column":1}},"7":{"start":{"line":11,"column":1},"end":{"line":11,"column":42}}},"branchMap":{"1":{"line":3,"type":"if","locations":[{"start":{"line":3,"column":2},"end":{"line":3,"column":2}},{"start":{"line":3,"column":2},"end":{"line":3,"column":2}}]}}};
   console.log('added code coverage for Foo.js');
}
var __cov_vcHPo7reSxzYcAbluk_XaA = __coverage__['C:\\git\\gt\\examples\\browser\\src\\Foo.js'];
__cov_vcHPo7reSxzYcAbluk_XaA.s['1']++;define([],function(){__cov_vcHPo7reSxzYcAbluk_XaA.f['1']++;__cov_vcHPo7reSxzYcAbluk_XaA.s['2']++;return function(){__cov_vcHPo7reSxzYcAbluk_XaA.f['2']++;__cov_vcHPo7reSxzYcAbluk_XaA.s['3']++;if(5>10){__cov_vcHPo7reSxzYcAbluk_XaA.b['1'][0]++;__cov_vcHPo7reSxzYcAbluk_XaA.s['4']++;return'bar';}else{__cov_vcHPo7reSxzYcAbluk_XaA.b['1'][1]++;}__cov_vcHPo7reSxzYcAbluk_XaA.s['5']++;return'foo';};});__cov_vcHPo7reSxzYcAbluk_XaA.s['6']++;function notCalled(){__cov_vcHPo7reSxzYcAbluk_XaA.f['3']++;__cov_vcHPo7reSxzYcAbluk_XaA.s['7']++;console.log('this does not get called!');}
